eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#logging:
#  pattern:
#    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
  tracing:
    sampling:
      probability: 1
server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cambio-service
          uri: lb://cambio-service
          predicates:
            - Path=/cambio-service/**
          filters:
            - RewritePath=/cambio-service/(?<path>.*), /$\{path}
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book-service/**
          filters:
            - RewritePath=/book-service/(?<path>.*), /$\{path}
        - id: open-api
          uri: lb://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
springdoc:
  swagger-ui:
    urls:
      - name: book-service
        url: /v3/api-docs/book-service
      - name: cambio-service
        url: /v3/api-docs/cambio-service