spring:
  application:
    name: and-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anderson-rodrigues-dev/and-config-server
          default-label: main
          search-paths:
            - 'greeting-service*'
server:
  port: 8888